// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmLw_L7Q2jMgGRTyuEnwq2CeY_5A8ECvs',
    appId: '1:376281322937:web:58c14f590c002beb231268',
    messagingSenderId: '376281322937',
    projectId: 'sastilaundry',
    authDomain: 'sastilaundry.firebaseapp.com',
    storageBucket: 'sastilaundry.appspot.com',
    measurementId: 'G-M6KWV51NW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ1lDyW4CRgZMuP57fbAK3CwAq66bQsI4',
    appId: '1:376281322937:android:84f8800444647f8c231268',
    messagingSenderId: '376281322937',
    projectId: 'sastilaundry',
    storageBucket: 'sastilaundry.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2d5GatUieMcRPMOL0NWxO2YHQXoz8PqA',
    appId: '1:376281322937:ios:d8bb820fc9fe6b33231268',
    messagingSenderId: '376281322937',
    projectId: 'sastilaundry',
    storageBucket: 'sastilaundry.appspot.com',
    iosClientId:
        '376281322937-4nplfv3i47dtvjbhvh0tlrgbpub85dgv.apps.googleusercontent.com',
    iosBundleId: 'com.mavikdev.sastilaundry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2d5GatUieMcRPMOL0NWxO2YHQXoz8PqA',
    appId: '1:376281322937:ios:5289b51fa4a22430231268',
    messagingSenderId: '376281322937',
    projectId: 'sastilaundry',
    storageBucket: 'sastilaundry.appspot.com',
    iosClientId:
        '376281322937-sdn32trnpl7g57pfvjojbkoqnv2dk5lv.apps.googleusercontent.com',
    iosBundleId: 'com.mavikdev.sastilaundry.RunnerTests',
  );
}
